{
 "title": "Demo App",
 "tags": [ "demo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "DB actions rate [counter]",
   "type": "graph",
   "description": "DB actions executed per-second over a selected interval per DB action type.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(actions_total[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DB actions execution time [summary]",
   "type": "graph",
   "description": "Amount of time taken for each DB action to complete over the selected interval. Based on action execution seconds to the number of actions completed.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_delete_summary_sum[$interval])/rate(db_delete_summary_count[$interval]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(db_insert_summary_sum[$interval])/rate(db_insert_summary_count[$interval]))",
     "legendFormat": "insert"
    }
   ]
  },
  {
   "title": "DB actions rate [gauge]",
   "type": "graph",
   "description": "Per-second rate of change to the number of DB actions.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(db_insert_gauge[$interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(deriv(db_delete_gauge[$interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "DB actions execution time (99th percentile) [histogram buckets]",
   "type": "graph",
   "description": "Amount of time taken for each DB action to complete over a 5-minute interval. Based on action execution seconds to the number of actions completed.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_delete_histogram_bucket[$interval])) by (le))",
     "legendFormat": "delete"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_insert_histogram_bucket[$interval])) by (le))",
     "legendFormat": "insert"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{name=\"prometheus-demo\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{name=\"prometheus-demo\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Memory Allocator Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{name=\"prometheus-demo\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{name=\"prometheus-demo\"}[$interval])",
     "legendFormat": "allocation rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{name=\"prometheus-demo\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{name=\"prometheus-demo\"}",
     "legendFormat": "heap inuse"
    }
   ]
  }
 ]
}