version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/martinsirbe/prometheus-graphite-demo
    steps:
      - checkout
      - run: go mod download
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: golangci-lint run -v
      - run: make test
