apiVersion: v1
kind: Service
metadata:
  name: &name graphite
  namespace: default
  labels:
    name: *name
spec:
  selector:
    name: *name
  ports:
    - name: ui
      port: 8080
      targetPort: 80
    - name: carbon
      port: 2003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name graphite
  namespace: default
  labels:
    name: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      name: *name
  template:
    metadata:
      labels:
        name: *name
    spec:
      containers:
        - name: graphite
          image: sitespeedio/graphite:1.1.5-12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 2003
