apiVersion: v1
kind: Service
metadata:
  name: &name prometheus-demo
  namespace: default
  labels:
    name: *name
  annotations:
    prometheus.io/port:   '1337'
    prometheus.io/scrape: 'true'
    prometheus.io/path:   '/metrics'
spec:
  selector:
    name: *name
  ports:
    - name: api
      port: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name prometheus-demo
  namespace: default
  labels:
    name: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      name: *name
  template:
    metadata:
      labels:
        name: *name
    spec:
      containers:
        - name: prometheus-demo
          image: martinsirbe/prometheus-demo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CARBON_URL
              value: "graphite:2003"
          ports:
            - containerPort: 1337
